config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'devise/registrations',
                                    confirmations: 'auth/confirmations' }

  devise_scope :user do
    get  '/login',            to: 'devise/sessions#new',         as: :login
    get  '/logout',           to: 'devise/sessions#destroy',     as: :logout
    get  '/register',         to: 'devise/registrations#new',    as: :register
    get  '/password/recover', to: 'devise/passwords#new',        as: :recover_password
    post '/password/recover', to: 'devise/passwords#create',     as: :reset_password
    get  '/password/change',  to: 'devise/passwords#edit',       as: :edit_password
    put  '/password/change',  to: 'devise/passwords#update',     as: :update_password

    patch '/confirm' => 'auth/confirmations#confirm', as: :confirm
  end

  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :confirmable,
         :trackable,
         :validatable

  audited

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_builder.rb
class FormBuilder < ActionView::Helpers::FormBuilder
  def errors(attribute)
    errors = object.errors.messages[attribute] || []

    unless errors.empty?
      "<span class=\"field__error\">#{attribute.to_s.humanize} #{errors.join(', ')}</span>".html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Space</title>
  <% content_for :stylesheets do %>
    <%= stylesheet_link_tag 'all', media: 'all', 'data-turbolinks-track' => true %>
  <% end %>
  <%= yield(:stylesheets) %>

  <%= javascript_include_tag 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="space <%= params[:controller] %>_page">
<%= render 'shared/header' %>
<%= yield %>
</div>
</body>
</html>

app/views/shared/_flash.erb
<% unless flash.empty? %>
  <div class="flash_container">
    <% [:notice, :error, :alert, :success].each do |level| %>
      <% unless flash[level].blank? %>
        <div class="flash flash--<%= level %>">
          <div class="flash__message flash__message">
            <%= flash[level].html_safe %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.erb
<h1 class="logo">
  <a href="<%= root_path %>">Space</a>
</h1>

<%= render 'shared/flash' %>

app/views/welcome/index.html.erb
<h2>
  <%= t(:welcome) %>
</h2>

<% if user_signed_in? %>
  <%= link_to t(:account), edit_registration_path(current_user) %>
  <%= link_to t(:logout), logout_path %>

  <p>Hi <%= current_user.email %></p>

  <%= debug current_user.audits %>
<% else %>
  <%= link_to t(:register), register_path %>
  <%= link_to t(:login), login_path %>
<% end %>